version: '3'
services:
    app:
        build: ./app
        command: "npm run serve"
        ports: 
            - "8080:8080"
        volumes:
            - "./app:/usr/src/app"
            - "/usr/src/app/node_modules"
        env_file: 
            - ".env"
    server:
        build: ./server
        command: "python app.py"
        ports:
            - "5000:5000"
        volumes:
            - "./server:/usr/src/server"
        env_file:
            - ".env"
